language: go
os: linux-ppc64le
sudo: required

go:
  - 1.x
go_import_path: k8s.io/minikube

install:
  - echo "Don't run anything."
script:
  - git clone https://github.com/kubernetes/minikube.git
  - mv minikube/.[!.]* ./
  - mv minikube/* ./
  - make
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
