language: go
os: linux-ppc64le
sudo: required

go:
  - 1.x

before_install:
  - sudo apt-get install -y libvirt-dev
install:
  - echo "Don't run anything."
script:
  - cd ..
  - rm -rf -f minikube
  - git clone https://github.com/kubernetes/minikube.git
  - cd minikube
  - make
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
